version: '3'

services:
  auto-revese-proxy:
    image: kalvinarts/auto-reverse-proxy:latest
    build:
      context: ./
      dockerfile: Dockerfile

    restart: unless-stopped
    command: node --max-http-header-size=131072 bin/index.js
    privileged: true

    environment:
      DEBUG: auto-reverse-proxy,docker-events,proxy-manager
      ARP_CERTS_PATH: /tmp/certs
      ARP_SOCKET_PATH: /var/run/docker.sock
      ARP_NETWORK_NAME: webproxy
      ARP_LETSENCRYPT_PORT: 9999

    volumes:
      - /var/run/docker.sock/:/var/run/docker.sock

    ports:
      - '80:80'
      - '443:443'
      - '9999:9999'

    networks:
      - webproxy

networks:
  webproxy:
    external: true
